baseURL = "https://mabvmex.github.io/git-blog/"
languageCode = "en-us"
title = "mi burbuja nerd"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = "G-1DDD2NJNSD"
  # Hey Explorer aquí pon tu twitter 👇
  twitter_handle = "@mabvmex"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
